// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.9.4-603-g0c9d452-dirty"
#define MICROPY_GIT_HASH "0c9d452-dirty"
#define MICROPY_BUILD_DATE "2018-09-28"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (9)
#define MICROPY_VERSION_MICRO (4)
#define MICROPY_VERSION_STRING "1.9.4"
